######################################################################
# Automatically generated by qmake (2.01a) Fri Oct 26 02:03:33 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += test.cpp
