######################################################################
# Automatically generated by qmake (2.01a) Fri Oct 26 02:01:21 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += hello.cpp
