######################################################################
# Automatically generated by qmake (2.01a) Thu Aug 2 21:36:20 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += layout1.cpp
