######################################################################
# Automatically generated by qmake (2.01a) Mon Dec 10 21:15:46 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += consumer.h producer.h
SOURCES += consumer.cpp main.cpp producer.cpp
