######################################################################
# Automatically generated by qmake (2.01a) Thu Aug 2 20:26:23 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += quit.cpp
