######################################################################
# Automatically generated by qmake (2.01a) Fri Aug 3 02:42:26 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += oventime.h
SOURCES += main.cpp oventime.cpp
