######################################################################
# Automatically generated by qmake (2.01a) Fri Aug 3 00:51:14 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += hexspinbox.h
SOURCES += hexspinbox.cpp main.cpp
