######################################################################
# Automatically generated by qmake (2.01a) Wed Dec 12 21:53:34 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += consumer.h producer.h testThread.h ui_win.h
SOURCES += consumer.cpp main.cpp producer.cpp testThread.cpp ui_win.cpp
