######################################################################
# Automatically generated by qmake (2.01a) Thu Aug 2 23:15:46 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += find.h
SOURCES += find.cpp main.cpp
