######################################################################
# Automatically generated by qmake (2.01a) Mon Dec 10 18:33:18 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += GUIThread.h Thread.h
SOURCES += GUIThread.cpp main.cpp Thread.cpp
