######################################################################
# Automatically generated by qmake (2.01a) Fri Dec 28 00:08:40 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += LOCKER.h STEALER.h
SOURCES += LOCKER.cpp main.cpp STEALER.cpp
