######################################################################
# Automatically generated by qmake (2.01a) Tue Dec 11 06:06:33 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += consumer.h producer.h
SOURCES += consumer.cpp main.cpp producer.cpp
