######################################################################
# Automatically generated by qmake (2.01a) Wed Oct 31 00:16:14 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwin.h pixmap.h
SOURCES += mainwin.cpp pixmap.cpp scrollarea.cpp
