######################################################################
# Automatically generated by qmake (2.01a) Wed Sep 26 04:33:39 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += gen_points.h points.h
SOURCES += gen_points.cpp main.cpp points.cpp
QT += opengl
